[2024-03-24 08:59:02,873] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T08:58:00+00:00 [queued]>
[2024-03-24 08:59:02,901] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T08:58:00+00:00 [queued]>
[2024-03-24 08:59:02,902] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:59:02,902] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-03-24 08:59:02,903] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:59:02,942] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-03-24T08:58:00+00:00
[2024-03-24 08:59:02,963] {standard_task_runner.py:52} INFO - Started process 18379 to run task
[2024-03-24 08:59:02,981] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'get_weather_data', '2024-03-24T08:58:00+00:00', '--job-id', '899', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/file.py', '--cfg-path', '/tmp/tmpqy42r71m', '--error-file', '/tmp/tmp1n2t2k6e']
[2024-03-24 08:59:02,982] {standard_task_runner.py:77} INFO - Job 899: Subtask get_weather_data
[2024-03-24 08:59:03,113] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T08:58:00+00:00 [running]> on host ce3400b6b8c4
[2024-03-24 08:59:03,266] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=get_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-24T08:58:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-24T08:58:00+00:00
[2024-03-24 08:59:06,878] {python.py:151} INFO - Done. Returned value was: None
[2024-03-24 08:59:06,960] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=get_weather_data, execution_date=20240324T085800, start_date=20240324T085902, end_date=20240324T085906
[2024-03-24 08:59:08,047] {local_task_job.py:199} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-03-24 08:59:08,059] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 18379
[2024-03-24 08:59:09,032] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-24 08:59:09,101] {process_utils.py:66} INFO - Process psutil.Process(pid=18379, status='terminated', exitcode=1, started='08:59:02') (18379) terminated with exit code 1
